### ISSUE TITLE
For consistency, add 'return rocket': =>

### ISSUE THREAD

**Issue by gb23** [learn-co-curriculum/js-object-oriented-constructor-functions-readme#5]
Prior lessons represent a return value as such:
// => returnValue

This lesson uses
//     returnValue

For consistency, bring back the return rocket!

**Comment by cjbrock** [comment]
Hi @gb23! While it's good to be consistent, it's also a good thing to be flexible. As a developer, you're going to run up against many different ways of formatting code, especially in JavaScript. You're going to be expected to go into an existing code base and understand what is happening, a lot of times both with and without a return rocket (sometimes within the same function!). While you're still learning, consistency is key, so we should bring it back here, but remember to always be flexible and try to understand what's happening and remember that JavaScript is more flexible than Ruby.

//<3 Corinna
