### ISSUE TITLE
Confusing sentence

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/js-object-oriented-constructor-functions-readme#7]
This sentence is confusing, to the point where I'm unable make a suggestion as to how to rewrite it:

"So now that we understand that this references the object receiving the method call, or with a constructor function, the newly created object, let's move onto the final step."

Thank you.

**Comment by drakeltheryuujin** [comment]
We have updated the materials and believe your issue to have been resolved.
Hopefully the confusion has been cleared up so that it's does not cause issues for other students.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
